### ISSUE TITLE
Criar URL para editar perfil

### ISSUE THREAD

**Issue by marianaalbano** [marianaalbano/elite#38]
Deve ser criada uma URL para o administrador/usuario editar o seu perfil. 

Para administradores do sistema, deve ser:

URL: /admin/id
GET (para exibir o formulário) e POST para alterar as informações 

Para usuarios comuns:

URL: /user/id
GET (para exibir o formulário) e POST para alterar as informações

**Comment by marianaalbano** [comment]
@hsfujie e @RenanDC decidam quem fará esta tarefa

**Comment by hsfujie** [comment]
Eu farei. @RenanDC
