### ISSUE TITLE
Número de Questionário

### ISSUE THREAD

**Issue by hsfujie** [marianaalbano/elite#47]
Ao criar uma pergunta nova, ele está numerando errado

**Comment by marianaalbano** [comment]
@hsfujie isso funciona desta forma porque quando eu adiciono uma pergunta dissertativa ou multipla escolha ela tem um ID único, mas nem toda questão está vinculada ao determinado questionário.

Por exemplo:

Dissertativas:

1 - Qual diretório que contem logs?
2 - Qual diretório que estão as configurações

Se eu colocar a pergunta 2 no questionário 1, vai aparecer:

"Pergunta 2"

Isso acontece porque esse 2 é relacionado ao ID da questão no banco e não a quantidade de questões atreladas ao questionário
